# Generated by Django 2.0 on 2019-03-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMABaseinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dma_no', models.CharField(max_length=50, unique=True, verbose_name='分区编号')),
                ('dma_name', models.CharField(max_length=50, unique=True, verbose_name='分区名称')),
                ('pepoles_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='服务人口')),
                ('acreage', models.CharField(blank=True, max_length=50, null=True, verbose_name='服务面积')),
                ('user_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户数量')),
                ('pipe_texture', models.CharField(blank=True, max_length=50, null=True, verbose_name='管道材质')),
                ('pipe_length', models.CharField(blank=True, max_length=50, null=True, verbose_name='管道总长度(m)')),
                ('pipe_links', models.CharField(blank=True, max_length=50, null=True, verbose_name='管道连接总数(个)')),
                ('pipe_years', models.CharField(blank=True, max_length=50, null=True, verbose_name='管道最长服务年限(年)')),
                ('pipe_private', models.CharField(blank=True, max_length=50, null=True, verbose_name='私人拥有水管长度(m)')),
                ('ifc', models.CharField(blank=True, max_length=250, null=True, verbose_name='IFC参数')),
                ('aznp', models.CharField(blank=True, max_length=250, null=True, verbose_name='AZNP')),
                ('night_use', models.CharField(blank=True, max_length=50, null=True, verbose_name='正常夜间用水量')),
                ('cxc_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='产销差目标值')),
                ('creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='负责人')),
                ('create_date', models.CharField(blank=True, max_length=30, null=True, verbose_name='建立日期')),
                ('belongto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dma', to='entm.Organization')),
            ],
            options={
                'db_table': 'dma_baseinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DmaGisinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dma_no', models.CharField(max_length=50, unique=True, verbose_name='分区编号')),
                ('geodata', models.TextField(blank=True, null=True)),
                ('strokeColor', models.CharField(blank=True, max_length=100, null=True)),
                ('fillColor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dma_gisinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DmaStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=30)),
                ('meter_type', models.CharField(max_length=30)),
                ('station_type', models.CharField(max_length=30)),
                ('dmaid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dmam.DMABaseinfo')),
            ],
            options={
                'db_table': 'dma_station',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='dmabaseinfo',
            unique_together={('dma_no',)},
        ),
    ]
